frameworkVersion: ">=3.14.0 <4.0.0"

service: okdata-data-collectors

provider:
  name: aws
  runtime: python3.11
  memorySize: 1024
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:provider.stage}, self:custom.deploymentBucket.dev}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  logRetentionInDays: 90
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      permissionsBoundary: "arn:aws:iam::${aws:accountId}:policy/oslokommune/oslokommune-boundary"
      managedPolicies:
        - 'arn:aws:iam::${aws:accountId}:policy/okdata-data-collectors-policy'
        - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    STAGE: ${self:provider.stage}
    VERSION: ${self:custom.version}
    SERVICE_NAME: ${self:service}
    OKDATA_ENVIRONMENT: ${self:custom.okdataEnvironment.${self:provider.stage}, self:custom.okdataEnvironment.dev}
    OKDATA_CLIENT_ID: ${self:service}
    OKDATA_CLIENT_SECRET: ${ssm:/dataplatform/okdata-data-collectors/keycloak-client-secret}

package:
  patterns:
    - '!**/*'
    - better_uptime/*.py
    - common/*.py

functions:
  collect-better-uptime-monitors:
    handler: better_uptime.handler.collect_monitors
    events:
      - schedule: cron(0 2 * * ? *)
    timeout: 60
    environment:
      UPTIME_DATASET_ID: oppetid-tjenester-i-origo

plugins:
  - serverless-better-credentials # must be first
  - serverless-plugin-git-variables
  - serverless-prune-plugin
  - serverless-python-requirements

resources:
  Description: |
    ${self:service} ${git:branch}:${git:sha1}
    ${git:message}

custom:
  version: 0.1.0
  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: false
  prune:
    automatic: true
    number: 3
  exportGitVariables: false
  deploymentBucket:
    prod: ok-origo-dataplatform-config-prod
    dev: ok-origo-dataplatform-config-dev
  okdataEnvironment:
    prod: prod
    dev: dev
