frameworkVersion: ">=3.14.0 <4.0.0"

service: okdata-data-collectors

provider:
  name: aws
  ecr:
    images:
      okdata-data-collectors:
        path: ./
        platform: linux/amd64
  memorySize: 1024
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:provider.stage}, self:custom.deploymentBucket.dev}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  logRetentionInDays: 90
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      permissionsBoundary: "arn:aws:iam::${aws:accountId}:policy/oslokommune/oslokommune-boundary"
      managedPolicies:
        - 'arn:aws:iam::${aws:accountId}:policy/okdata-data-collectors-policy'
        - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    STAGE: ${self:provider.stage}
    VERSION: ${self:custom.version}
    SERVICE_NAME: ${self:service}
    OKDATA_ENVIRONMENT: ${self:custom.okdataEnvironment.${self:provider.stage}, self:custom.okdataEnvironment.dev}
    OKDATA_CLIENT_ID: ${self:service}

functions:
  collect-measurements:
    image:
      name: okdata-data-collectors
      command:
        - measurements.handler.import_data
    events:
      - schedule: cron(0 2 * * ? *)
    timeout: 120
    environment:
      OKR_TRACKER_API_BASE_URL: ${ssm:/dataplatform/okr-tracker/api-url}
  collect-better-uptime-monitors:
    image:
      name: okdata-data-collectors
      command:
        - better_uptime.handler.collect_monitors
    events:
      - schedule: cron(0 2 * * ? *)
    timeout: 60
    environment:
      UPTIME_DATASET_ID: oppetid-tjenester-i-origo
  collect-agresso:
    image:
      name: okdata-data-collectors
      command:
        - agresso.handlers.import_datasets
    events:
      - schedule: cron(0 2 * * ? *)
    timeout: 600
    environment:
      AGRESSO_BASE_URL: "https://okonomi-query-engine.api.oslo.kommune.no"
      AGRESSO_PDF_BASE_URL: "https://origo.oslo.systems/agresso-pdf/voucher"
  collect-ssb:
    image:
      name: okdata-data-collectors
      command:
        - ssb.handlers.import_datasets
    events:
      - schedule: cron(0 2 ? * SUN *)
    timeout: 60
    environment:
      SSB_BASE_URL: "https://data.ssb.no/api/v0"
  collect-statistikkbanken:
    image:
      name: okdata-data-collectors
      command:
        - statistikkbanken.handler.import_datasets
    events:
      - schedule: cron(0 2 ? * SUN *)
    timeout: 120
    environment:
      STATISTIKKBANKEN_BASE_URL: "https://statistikkbanken.oslo.kommune.no:443/statbank/sq"
  collect-barnehageregister:
    image:
      name: okdata-data-collectors
      command:
        - barnehageregister.handler.import_datasets
    events:
      # NBR is updated from BRREG between 01:00 and 02:00.
      - schedule: cron(0 4 ? * SUN *)
    timeout: 600
    environment:
      BARNEHAGEREGISTER_BASE_URL: "https://data-nbr.udir.no/v4"
  collect-barnehagefakta:
    image:
      name: okdata-data-collectors
      command:
        - barnehagefakta.handler.import_datasets
    events:
      # Refresh data from Barnehagefakta only monthly.
      - schedule: cron(0 2 1 * ? *)
    timeout: 180
    environment:
      BARNEHAGEFAKTA_BASE_URL: "https://www.barnehagefakta.no/api"

plugins:
  - serverless-better-credentials # must be first
  - serverless-plugin-git-variables
  - serverless-prune-plugin

resources:
  Description: |
    ${self:service} ${git:branch}:${git:sha1}
    ${git:message}

custom:
  version: 0.1.0
  prune:
    automatic: true
    number: 3
  exportGitVariables: false
  deploymentBucket:
    prod: ok-origo-dataplatform-config-prod
    dev: ok-origo-dataplatform-config-dev
  okdataEnvironment:
    prod: prod
    dev: dev
