import pytest


@pytest.fixture
def kindergarten():
    return {
        "id": "de368ed6-e544-4a1c-b64a-c3f5285a1276",
        "alder": "1 - 2",
        "ansatte": {"antallFra": 1, "antallTil": 4},
        "eierform": "Privat",
        "erAktiv": True,
        "erBarnehage": True,
        "erBarnehageEier": False,
        "erPrivatBarnehage": True,
        "fylke": {"fylkesnavn": "Oslo", "fylkesnummer": "03"},
        "kommune": {"kommunenavn": "Oslo", "kommunenummer": "0301"},
        "kontaktinformasjon": {
            "postAdresse": None,
            "besoksAdresse": {
                "adresselinje": "Kryssveien 10b",
                "postnr": "0583",
                "poststed": "OSLO",
            },
            "url": "",
        },
        "koordinatLatLng": [59.93608, 10.8196],
        "malform": {"malformType": "B", "malformNavn": "Bokmål"},
        "navn": "Maurtua Familiebarnehage",
        "orgnr": "888496092",
        "indikatorDataBarnehage": {
            "antallBarn": 4,
            "antallBarnPerAnsatt": None,
            "antallBarnPerBarnehagelaerer": None,
            "andelAnsatteMedBarneOgUngdomsarbeiderfag": 0.0,
            "andelAnsatteBarnehagelarer": 11.5,
            "andelAnsatteTilsvarendeBarnehagelaerer": 0.0,
            "andelAnsatteMedAnnenHoyereUtdanning": 88.5,
            "andelAnsatteMedAnnenFagarbeiderutdanning": 0.0,
            "andelAnsatteMedAnnenBakgrunn": 0.0,
            "andelAnsatteMedAnnenPedagogiskUtdanning": 0.0,
            "lekeOgOppholdsarealPerBarn": None,
            "andelBarnehagerSomOppfyllerPedagognormen": None,
            "andelBarnehagerSomIkkeOppfyllerPedagognormen": None,
            "andelBarnehagerSomOppfyllerPedagognormenMedDispensasjon": None,
            "foreldreundersokelsenUteOgInneMiljo": 5.0,
            "foreldreundersokelsenBarnetsUtvikling": None,
            "foreldreundersokelsenBarnetsTrivsel": 5.0,
            "foreldreundersokelsenInformasjon": 5.0,
            "foreldreundersokelsenTilfredshet": 5.0,
            "foreldreundersokelsenAntallInviterte": 7,
            "foreldreundersokelsenAntallBesvarte": 5,
            "foreldreundersokelsenSvarprosent": 71.4,
            "foreldreundersokelsenArgang": "2023",
        },
        "indikatorDataKommune": {
            "antallBarn": 35183,
            "antallBarnPerAnsatt": 5.8,
            "antallBarnPerBarnehagelaerer": 14.5,
            "andelAnsatteMedBarneOgUngdomsarbeiderfag": 16.6,
            "andelAnsatteBarnehagelarer": 37.8,
            "andelAnsatteTilsvarendeBarnehagelaerer": 1.6,
            "andelAnsatteMedAnnenHoyereUtdanning": 3.7,
            "andelAnsatteMedAnnenFagarbeiderutdanning": 2.0,
            "andelAnsatteMedAnnenBakgrunn": 34.0,
            "andelAnsatteMedAnnenPedagogiskUtdanning": 4.3,
            "lekeOgOppholdsarealPerBarn": 5.5,
            "andelBarnehagerSomOppfyllerPedagognormen": 47.4,
            "andelBarnehagerSomIkkeOppfyllerPedagognormen": 9.3,
            "andelBarnehagerSomOppfyllerPedagognormenMedDispensasjon": 43.3,
            "foreldreundersokelsenUteOgInneMiljo": 4.1,
            "foreldreundersokelsenBarnetsUtvikling": 4.6,
            "foreldreundersokelsenBarnetsTrivsel": 4.7,
            "foreldreundersokelsenInformasjon": 4.4,
            "foreldreundersokelsenTilfredshet": 4.5,
            "foreldreundersokelsenAntallInviterte": 33069,
            "foreldreundersokelsenAntallBesvarte": 24146,
            "foreldreundersokelsenSvarprosent": 73.0,
            "foreldreundersokelsenArgang": "2023",
        },
        "kostpenger": 0.0,
        "type": "Familiebarnehage",
        "pedagogiskProfil": None,
        "apningstidFra": "07:30",
        "apningstidTil": "16:30",
        "oppfyllerPedagognorm": "",
        "totalAntallKvadratmeter": None,
        "urlTilSoknadOmBarnehageplass": "http://www.oslo.kommune.no/",
    }
